# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogout():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_logout(self):
    # Test name: logout
    # Step # | name | target | value
    # 1 | open | https://120.101.8.132/ | 
    self.driver.get("https://120.101.8.132/")
    # 2 | setWindowSize | 968x1020 | 
    self.driver.set_window_size(968, 1020)
    # 3 | click | css=.ivu-icon-md-arrow-dropdown | 
    self.driver.find_element(By.CSS_SELECTOR, ".ivu-icon-md-arrow-dropdown").click()
    # 4 | click | css=.ivu-dropdown-item-divided | 
    self.driver.find_element(By.CSS_SELECTOR, ".ivu-dropdown-item-divided").click()
  
